services:
    server:
        build:
            context: ../..
            dockerfile: apps/server/Dockerfile
        env_file: .env
        ports:
            - "3000:3000"
            - "3001:3001"
            - "4000:4000"
        restart: unless-stopped
